-- TRADEWISE FINAL AUTH + TRIAL + LEAD TRACKING
-- Run this once in Supabase SQL Editor.
-- The existing subscriptions table is preserved; this adds only the missing
-- lead/activity tables and a safe trial-status convention.

create table if not exists public.leads (
  id uuid primary key default gen_random_uuid(),
  visitor_id text,
  user_id uuid references auth.users(id) on delete set null,
  name text,
  email text,
  source text default 'direct',
  campaign text default 'organic',
  medium text default 'unknown',
  first_visit timestamptz default now(),
  status text default 'NEW',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create unique index if not exists leads_email_unique
on public.leads (lower(email))
where email is not null;

create table if not exists public.activity_events (
  id bigint generated by default as identity primary key,
  visitor_id text,
  user_id uuid references auth.users(id) on delete set null,
  event text not null,
  metadata jsonb default '{}'::jsonb,
  timestamp timestamptz default now()
);

alter table public.leads enable row level security;
alter table public.activity_events enable row level security;

-- A user may create/update only their own lead record.
drop policy if exists "lead_self_insert" on public.leads;
create policy "lead_self_insert" on public.leads
for insert to authenticated
with check (user_id = auth.uid() or user_id is null);

drop policy if exists "lead_self_update" on public.leads;
create policy "lead_self_update" on public.leads
for update to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

-- A user may write their own activity events.
drop policy if exists "activity_self_insert" on public.activity_events;
create policy "activity_self_insert" on public.activity_events
for insert to authenticated
with check (user_id = auth.uid());

-- Users can read only their own activity events.
drop policy if exists "activity_self_select" on public.activity_events;
create policy "activity_self_select" on public.activity_events
for select to authenticated
using (user_id = auth.uid());

-- IMPORTANT:
-- Keep your existing subscriptions RLS/policies unchanged.
-- The TradeWise frontend uses the already-proven subscriptions table.
-- The subscription row for a trial user is:
-- status = 'trial', plan = 'basic', starts_at = ..., expires_at = ...
